import { NextResponse } from 'next/server';
import { getAuthUser } from '@/lib/auth.js';
import prisma from '@/lib/prisma.js';
import fs from 'fs/promises';
import path from 'path';

export async function POST(request, { params }) {
  const user = getAuthUser(request);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;

  try {
    // 1. Fetch backup details
    const backup = await prisma.backup.findUnique({
      where: { id },
    });

    if (!backup) {
      return NextResponse.json({ error: 'Backup not found' }, { status: 404 });
    }

    // 2. Read backup file from disk
    const filePath = path.join(process.cwd(), 'public', backup.fileUrl);
    const fileContent = await fs.readFile(filePath, 'utf-8');
    const backupData = JSON.parse(fileContent);

    const { projectId, data } = backupData;

    if (!projectId || !data) {
      return NextResponse.json({ error: 'Invalid backup file format' }, { status: 400 });
    }

    // 3. Restore data inside transaction to preserve database integrity
    await prisma.$transaction(async (tx) => {
      // Restore Global Settings
      if (data.settings) {
        // Strip relations or ID mismatch
        const { id: sId, projectId: pId, createdAt, updatedAt, ...settingsFields } = data.settings;
        await tx.globalSetting.upsert({
          where: { projectId },
          update: settingsFields,
          create: { projectId, ...settingsFields },
        });
      }

      // Restore Email Settings
      if (data.emailSettings) {
        const { id: eId, projectId: pId, createdAt, updatedAt, ...emailFields } = data.emailSettings;
        await tx.emailSetting.upsert({
          where: { projectId },
          update: emailFields,
          create: { projectId, ...emailFields },
        });
      }

      // Helper to restore items by id
      const restoreItems = async (dbModel, items) => {
        if (!items || !items.length) return;
        for (const item of items) {
          const { id, ...itemData } = item;
          // Filter out nested relation objects that might be present
          const cleanItemData = {};
          for (const [key, value] of Object.entries(itemData)) {
            if (value !== null && typeof value === 'object' && !(value instanceof Date)) {
              continue;
            }
            cleanItemData[key] = value;
          }

          await tx[dbModel].upsert({
            where: { id },
            update: cleanItemData,
            create: { id, ...cleanItemData },
          });
        }
      };

      // Restore FAQ items (matching table fAQ)
      if (data.faqs) {
        await restoreItems('fAQ', data.faqs);
      }

      // Restore other models
      if (data.pages) {
        // Strip out relational models before upserting page
        const pageItemsClean = data.pages.map(({ seo, sections_rel, versions, ...p }) => p);
        await restoreItems('page', pageItemsClean);
      }
      if (data.services) await restoreItems('service', data.services);
      if (data.blogs) await restoreItems('blog', data.blogs);
      if (data.testimonials) await restoreItems('testimonial', data.testimonials);
      if (data.contacts) await restoreItems('contact', data.contacts);
      if (data.leads) await restoreItems('lead', data.leads);
      if (data.formSubmissions) await restoreItems('formSubmission', data.formSubmissions);
      if (data.navigation) await restoreItems('navigation', data.navigation);
      if (data.redirects) await restoreItems('redirect', data.redirects);
    });

    // Log activity
    await prisma.activityLog.create({
      data: {
        projectId,
        action: 'RESTORE',
        details: `Restored backup from ${new Date(backup.createdAt).toLocaleString()} generated by ${backupData.generatedBy || 'system'}.`,
      },
    });

    return NextResponse.json({ success: true, message: 'Restore completed successfully' });
  } catch (error) {
    console.error('Backup restore failed:', error);
    return NextResponse.json({ error: 'Restore failed: ' + error.message }, { status: 500 });
  }
}
